from OpenGL.GL import *
from OpenGL.GLU import *
from OpenGL.GLUT import *

x = 0
r = 0
inc = 0.001


def init():
    glClearColor(0, .255, .255, 1)
    glMatrixMode(GL_PROJECTION)
    glLoadIdentity()
    gluPerspective(90, 2, 0.1, 100)
    gluLookAt(5, 5, 5, 0, 0, -1, 0, 1, 0)
    glMatrixMode(GL_MODELVIEW)

def display():
    global x, r, inc
    glClear(GL_COLOR_BUFFER_BIT)
    glLoadIdentity()
    glColor(.224,.224,.224)
    glTranslate(0, 0, 0)
    glScale(100, 1, 4)
    glutSolidCube(3)

    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(4, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(2, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)

    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(0, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)

    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-2, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-4, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-6, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-8, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-10, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-12, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-14, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-16, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-18, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-20, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-22, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-24, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-26, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-28, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-30, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-32, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-34, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-36, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)

    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-38, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)

    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-40, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-42, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-44, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-46, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-48, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-48, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)

    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-50, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)

    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-52, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-54, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-56, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-58, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-60, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-62, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-64, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-66, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-68, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-70, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-72, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-74, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-76, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-78, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-80, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-82, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-84, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-86, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)

    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-88, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)

    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-90, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-92, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-94, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-96, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-98, 0, 6.8)
    glScale(1, .2, .5)
    glutSolidCube(2)



    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(0, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)

    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(2, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(4, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(6, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(8, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(10, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(12, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(14, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(16, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(18, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(20, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(22, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(24, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(26, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)

    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(0, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)

    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-2, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-4, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-6, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-8, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-10, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-12, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-14, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-16, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-18, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-20, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-22, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-24, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-26, 0,-11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-28, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-30, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-32, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-34, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-36, 0,-11)
    glScale(1, .2, .5)
    glutSolidCube(2)

    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-38, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)

    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-40, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-42, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-44, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-46, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-48, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-48, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)

    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-50, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)

    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-52, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-54, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-56, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-58, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-60, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-62, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-64, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-66, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-68, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-70, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-72, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-74, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-76, 0,-11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-78, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-80, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-82, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-84, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-86, 0,-11)
    glScale(1, .2, .5)
    glutSolidCube(2)

    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-88, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)

    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-90, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-92, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-94, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(-96, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(-98, 0, -11)
    glScale(1, .2, .5)
    glutSolidCube(2)


    glLoadIdentity()
    glColor(1,1,1)
    glTranslate(0, 0, .7)
    glScale(1, .2, .5)
    glutSolidCube(2)

    glLoadIdentity()
    glColor(1,1,1)
    glTranslate(5, 0, .7)
    glScale(1, .2, .5)
    glutSolidCube(2)

    glLoadIdentity()
    glColor(1,1,1)
    glTranslate(-5, 0, .7)
    glScale(1, .2, .5)
    glutSolidCube(2)

    glLoadIdentity()
    glColor(1,1,1)
    glTranslate(-10, 0, .7)
    glScale(1, .2, .5)
    glutSolidCube(2)

    glLoadIdentity()
    glColor(1,1,1)
    glTranslate(-15, 0, .7)
    glScale(1, .2, .5)
    glutSolidCube(2)

    glLoadIdentity()
    glColor(1, 1, 1)
    glTranslate(-20, 0, .7)
    glScale(1, .2, .5)
    glutSolidCube(2)

    glLoadIdentity()
    glColor(1, 1, 1)
    glTranslate(-25, 0, .7)
    glScale(1, .2, .5)
    glutSolidCube(2)

    glLoadIdentity()
    glColor(1, 1, 1)
    glTranslate(-30, 0, .7)
    glScale(1, .2, .5)
    glutSolidCube(2)

    glLoadIdentity()
    glColor(1, 1, 1)
    glTranslate(-35, 0, .7)
    glScale(1, .2, .5)
    glutSolidCube(2)

    glLoadIdentity()
    glColor(1, 1, 1)
    glTranslate(-40, 0, .7)
    glScale(1, .2, .5)
    glutSolidCube(2)

    glLoadIdentity()
    glColor(1, 1, 1)
    glTranslate(-45, 0, .7)
    glScale(1, .2, .5)
    glutSolidCube(2)

    glLoadIdentity()
    glColor(1, 1, 1)
    glTranslate(-50, 0, .7)
    glScale(1, .2, .5)
    glutSolidCube(2)

    glLoadIdentity()
    glColor(1, 0, 0)
    glScale(1, 0.5, 1)
    glTranslate(0 + x, 3, 0)
    glutWireCube(3)
    glLoadIdentity()
    glColor(1, 0, 0)
    glTranslate(0 + x, 0, 0)
    glScale(3, 0.5, 1)
    glutWireCube(3)

    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(4.5 + x, 0, 1)
    glutWireSphere(0.3, 8, 8)

    glLoadIdentity()
    glColor(1, 1, 0)
    glTranslate(4.5 + x, 0, -1)
    glutWireSphere(0.3, 8, 8)

    glLoadIdentity()
    glColor(0, 0, 1)
    glTranslate(3.7 + x, -0.7, 1.5)
    glRotate(r, 0, 0, -1)
    glutWireTorus(0.1, 0.5, 10, 10)

    glLoadIdentity()
    glColor(0, 0, 1)
    glTranslate(3.7 + x, -0.7, -1.5)
    glRotate(r, 0, 0, -1)
    glutWireTorus(0.1, 0.5, 10, 10)

    glLoadIdentity()
    glColor(0, 0, 1)
    glTranslate(-3.7 + x, -0.7, -1.5)
    glRotate(r, 0, 0, -1)
    glutWireTorus(0.1, 0.5, 10, 10)

    glLoadIdentity()
    glColor(0, 0, 1)
    glTranslate(-3.7 + x, -0.7, 1.5)
    glRotate(r, 0, 0, -1)
    glutWireTorus(0.1, 0.5, 10, 10)


    x += inc
    r += inc * 100

    if x > 5 or x < -10:
        inc *= -1

    glutSwapBuffers()
glutInit()
glutInitDisplayMode(GLUT_RGB | GLUT_SINGLE | GLUT_DOUBLE)
glutInitWindowSize(750, 730)
glutCreateWindow(b"CAr")
glutDisplayFunc(display)
glutIdleFunc(display)
init()
glutMainLoop()